experiment_params:
  project_name: stm
  experiment_name: eff_b3_ns_bowl2018_iou
  dump_path: /home/liz/STM/experiments
  seed: 69

data_params:
  data_folder: /home/liz/Diplom_Unet/data/bowl2018
  dataset_folder: /home/liz/STM/datasets
  dataset_name: bowl2018.json
  batch_size: 16
  num_workers: 4
  transform:
    train: /home/liz/STM/configs/train_transform.yaml
    valid: /home/liz/STM/configs/valid_transform.yaml
    test: /home/liz/STM/configs/valid_transform.yaml

train_params:
  target_metric: 'iou'
  model: Unet
  model_params:
    encoder_name: 'timm-efficientnet-b3'
    encoder_weights: 'imagenet'
    classes: 2

stages:
  main:
    epochs: 70
    loss: DiceLoss
    loss_params:
      activation: 'sigmoid'
    optimizer: AdamW
    optimizer_params:
      lr: 0.001
      weight_decay: 0.01
    scheduler: ReduceLROnPlateau
    scheduler_params:
      patience: 3
      factor: 0.5
      threshold: 0.001
      mode: min